### ISSUE TITLE
Jinja uses Django comments

### ISSUE THREAD

**Issue by redreceipt** [preservim/nerdcommenter#414]
Jinja2 files use [Django multiline comments](https://stackoverflow.com/questions/719915/how-to-put-comments-in-django-templates). Guessing because the file is interpreted as `htmldjango` instead of pure Jinja2. It's broken working with Flask files. It produces comments like this:

```
{% comment %}<p>Hello</p>{% endcomment %}
```

[Should be](https://jinja.palletsprojects.com/en/2.10.x/templates/#comments):

```
{# <p>Hello</p> #}
```

Since the latter works with Django too, that should be the default.

**Comment by alerque** [comment]
I don't think there is any reason to change the Django comment style, that is something for Django people to settle on. See also #359 for where that was last changed.

The thing do do is fix your file type detection so that when you open a jina file you actually get a jinja filetype (or flask?). Right now there is one in NERD Commenter already, but this plugin does not provide any file type detection, in relies on what the host editor and/or other plugins detect and set.

What is the correct filetype for the kinds of file you are actually editing an what is responsible for setting that? Does vim have a filetype for it? If not do any plugins implement an ftdetect for one?

**Comment by redreceipt** [comment]
Not sure, that's a good question. You're right, it should detect `jinja` or `htmlflask` or something and doesn't. I'll track that down. But once that's correct, nerd commenter won't do anything until support is added for that type correct?

**Comment by redreceipt** [comment]
How could I figure out what is setting my file type incorrectly?

**Comment by redreceipt** [comment]
Ok I got my filetype changed to `jinja.html` and now it uses standard `html` comments. Would you like me to make a separate issue and close this one?

**Comment by alerque** [comment]
This issue is fine untile we figure out what the right combo is for this file types.

I don't think `jinja.html` is right either. That's an antificial filetype for layered types, which is something VIM actually uses very sparingly. If anything I'm guessing it should be the other way around (`html.jinja`). Can you point me to what plugin or documentation is suggesting this instead of just "jinja"?

It appears that the comment type for jina in this plugin has two kinds: the primary for HTML mode and the secondary for Jinja mode. What you probably want at this point is to flip to using alternate delimiters.

**Comment by redreceipt** [comment]
What needs to happen is `jinja.html` (or `html.jinja`) should comment with `{# stuff #}`. No flipping necessary.

The library that sets that type is github.com/Glench/Vim-Jinja2-Syntax

**Comment by redreceipt** [comment]
@alerque is that change going to work with the file type set to `jinja.html`?

**Comment by alerque** [comment]
@redreceipt It should yes. Feel free to report if you have any trouble with it.

**Comment by redreceipt** [comment]
I tested it, it works. Thank you! I see there hasn't been a release since 2018, is there a different way to pick up the changes? Sorry for my ignorance, still learning vim plugin foo.

**Comment by alerque** [comment]
What plugin manager are you using? Almost all of them that I'm aware of use git repository master branches to update from anyway and ignore version tags, so there isn't a lot of motivation to "release" anything these days.

**Comment by redreceipt** [comment]
Gotcha. I use Vim-plug.

**Comment by alerque** [comment]
So do I. Vim-plug is among the many that just full straight from master branches. Running `:PlugUpdate` periodically should keep you up to speed. There is no mechanism to "push" updates, so tagging a release here won't really reach anybody directly other than a few who are following releases only on Github.
