### ISSUE TITLE
when g:NERDCustomDelimiters['x']['left'] set to begin with space nerdcommenter works uncorrectly.

### ISSUE THREAD

**Issue by termanary** [preservim/nerdcommenter#430]
vimrc:
```
filetype plugin indent on
let g:NERDCustomDelimiters = {'lex': { 'left': ' /**', 'right': '*/' } }
```
note:the left value of comment style begin with a space.
Nerdcommenter could correctly comment it but it could not correctly uncomment it.
origin text:
```
a
```
And we will get:
```
 /** [[> > a <] <] */
```
Although no a programming language comment style begins with a space,it's necessary for nerdcommenter to handle it correctly.Sometimes the char for comment could not write in the beginning of a line but user wants to comment the line.
This problem may be caused by the wrong determination whether the text is commented:
```
function s:IsCommented
```

**Comment by alerque** [comment]
Adding a space character to surrounding a delimiter is not supported for many reasons, most notably because it conflicts with the way we actually handle this. The correct supported way to get a space after the delimiter for your comments is to enable the corresponding feature:

```viml
let g:NERDSpaceDelims = 1
```

You can also customize the string used for the optional leading space, for example to get more than one space:

```viml
let s:spacePreStr = '  '
```

This should account for the the situation where existing comments may or may not have used the user's preferred leading space scenario.

This only gets complicated where some languages and style guides do in fact demand the space to be valid syntax, sometimes even more than one (Looking at you, silly PEP8!). For those cases there is already an issue to track this, see #328.
