### ISSUE TITLE
Commenting out comments change code requiring 2 uncomment operations to return to original source

### ISSUE THREAD

**Issue by willpnw** [preservim/nerdcommenter#431]
Example: someFile.js(I also see this with other extensions)

Original Code:
`/* ctor */`

`<leader>cl`
Commented code:
`//[> ctor <]`

`<leader>cu`
Uncommented code:
`[> ctor <]`

After comment, and then uncomment, the code should be the same as it was before commenting. I then have to go back and uncommment again. If this is in a big block, it's easy to not notice causing weird side effects

**Comment by alerque** [comment]
Thanks for taking the time to submit this issue. I believe this is a know issue with nested comments, implemented in #151. See #68 for further details and status of the known bug. The short version is that this is working for some languages that have higher level support for nested comments, but not yet for general purpose use in languages that don't. We'd be happy to accept a contribution from anybody that could fix this. Since the other issue tracking this is still open I'm going to close this one as a duplicate.

Also somewhat related to #291.
