### ISSUE TITLE
how to edit the count

### ISSUE THREAD

**Issue by linwan623910** [preservim/nerdcommenter#439]
My vim was set relativenumber,when i do [d2j],it will delete 2 lines include the current line,total 3 lines.
so,for the [nerdcommenter], when a [count] is given in normal mode, how to get the same result?

For example:
do 2<leader>cc for the current line and the next two lines
not only for the next 1 line

**Comment by alerque** [comment]
This is not a function of this plugin, this is how *count* modifiers work in vim. I suggest you adapt the model in your head to work the way VIM things about them rather than trying to hack the counts to be `n+1`.

Your example of `d2j` starts delete mode in the current line, then moves the cursor down twice. The count is modifying the move action not the delete. Similarly entering Visual mode with `v` then moving the cursor with `j` will end up with 2 lines selected, the original one you were in and the one you moved to below it. If you want to delete three lines you could modify the delete-line command with a count by using `3D`.

The comment functions in this plugin make take their actions on the current line or visual selection **just like every other VIM command**. The count modifies the action, and if the action is "comment the current line" there is no reason to make this work on "current + 1" lines. Even if you did you'd loose the ability to comment 1 line ;-)
