### ISSUE TITLE
vim8.2: Using incorrect comment character for filetype 'vim'

### ISSUE THREAD

**Issue by mikewy0527** [preservim/nerdcommenter#456]
Using incorrect comment character for filetype 'vim'.
vim version:
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 18:17:04)
Included patches: 1-2347
Compiled by Arch Linux
```

The reason is: Vim9 script change the comment from " to # (can be found on [vim9.txt](https://vimhelp.org/vim9.txt.html)):
```
2. Differences from legacy Vim script                   vim9-differences

THIS IS STILL UNDER DEVELOPMENT - ANYTHING CAN BREAK - ANYTHING CAN CHANGE

Overview 

Brief summary of the differences you will most often encounter when using Vim9
script and :def functions; details are below:
- Comments start with #, not ": 
        echo "hello"   # comment
...
```

The change also can be found  in /usr/share/vim/vim82/ftplugin/vim.vim:
```
...
51 if "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
52   " Set 'comments' to format dashed lists in comments
53   setlocal com=sO:#\ -,mO:#\ \ ,eO:##,:#
54   " Comments start with a double quote in a legacy script;
55   " with # in a Vim9 script
56   setlocal commentstring=\"%s
57 else
58   setlocal com=sO:\"\ -,mO:\"\ \ ,:\"
59   setlocal commentstring=#%s
60 endif
...
```

The work-around is add the delimiter definition fo filetype 'vim' to s:delimiterMap:
```
let s:delimiterMap = {
    ...
    \ 'vim': { 'left': '"' },
    ...
    \ }
```

**Comment by alerque** [comment]
This is a good change for VimL, but it should have happened decades ago. Using a comment delimiter that also had other syntactical meaning to the language was a stupid design choice from day 1.

That being said it's really complicated to fix for this plugin. This is one of the interesting cases where we don't actually define a comment type for the file and let it inherit from `commentstring`. This actually serves pretty well here because not all versions of Vim are using the new language, and those that are may or may not want to use its syntax.

In addition to the work around you mention, you can also set the `commentstring` value in an autoload function for the `vim` filetype.

Eventually the `vim` filetype may need to be extended to a new `vim9` (or similar) filetype. At that point we can add a filetype to support it. Until then Vim9-script is still under development and not the current production version of VimL. That 8.2 has partially implemented this change by default for a language change they still have documented as under development is an upstream problem, not ours *per se*. Hence we'll keep the current delimiter situation for now.

**Comment by mikewy0527** [comment]
@alerque Thanks for your advice. I setting the `commentstring` and it works.

**Comment by alerque** [comment]
I think we'll leave it up to your VIM distribution for when to change the *default* `commentstring` and up to users if they want to override their package's defaults. There are going to be strong preferences involved and different workflows and I don't see anything this plugin can really add by getting in the way messing with those shenanigans.

**Comment by mikewy0527** [comment]
This issue is the bug of vim. In vim's new version, the `commentstring` setting was changed, and it work correctly after I comment the `commentstring` in my vimrc.

The new vim version:
```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 09 2021 23:51:55)
Included patches: 1-2489
Compiled by Arch Linux
```
The new code in /usr/share/vim/vim82/ftplugin/vim.vim
```
...
if "\n" .. getline(1, 10)->join("\n") =~# '\n\s*vim9\%[script]\>'
 52   " Set 'comments' to format dashed lists in comments
 53   setlocal com=sO:#\ -,mO:#\ \ ,eO:##,:#
 54   " Comments starts with # in Vim9 script
 55   setlocal commentstring=#%s                                                                                                                            
 56 else
 57   setlocal com=sO:\"\ -,mO:\"\ \ ,:\"
 58   " Comments starts with a double quote in legacy script
 59   setlocal commentstring=\"%s
 60 endif
...
```
