### ISSUE TITLE
How to map the function toggling comment state to a keymap in normal mode and visual mode? 

### ISSUE THREAD

**Issue by a-aiman** [preservim/nerdcommenter#484]
my .vimrc

```viml
nnoremap <silent> <C-_> :<C-u>call nerdcommenter#Comment(0, "toggle")<CR>

vnoremap <silent> <C-_> : call nerdcommenter#Comment("x", "toggle")<CR>
```

it works for now, i took it from the readme and stack overflow.
apparently if i changed the first argument in normal mode remap to an "x" it does not work as expected. ( pressing the keybindings will not toggle current line but instead the previous selection).
First question: Why is that? What's the difference between 0 and x?
Second question: Are there any ref or docs for this plugin?

**Comment by alerque** [comment]
Like most vim plugns, documentation is available inside vim's help system, run `:help nerdcommenter`.

You probably won't find what you need in there though because you already know the functions you want to run, what you need is the standard VIM way to bind to keys. I'm confused about what key(s) you actually want to bind though.

By the way are you aware of the *default* binding using the `<Leader>` key (usually `\` by default in VIM) and various key sequences. Toggle happens to be `c<Space>`, so `\c<Space>` should toggle in both visual and regular mode.

An easy way to get access to that is just to map the mappings:

```viml
map x <Leader>c<Space>
```

That will set `x` in both regular and visual modes to toggle comment status.

**Comment by a-aiman** [comment]
Im trying to bind ctrl-/ to toggle instead of the default <leader>c<space> to mimic vscode bindings(which is what im used to). Thanks for that recommendation though, somehow my dumb brain did not thought of that haha.
