### ISSUE TITLE
Basic nested comment is not worked.

### ISSUE THREAD

**Issue by zhou13** [preservim/nerdcommenter#68]
In a c source file.

```
  a++
```

Comment it, we get

```
/* [> a++ <] */
```

Uncomment it, oops!.we get

```
[> a++ <]
```

**Comment by alerque** [comment]
There is a work in progress (see #151 for handling language that can actually nest comments).

**Comment by alerque** [comment]
Basic support for _real_ nested comments has been merged for languages that support it. This issue seems to be with languages that have the faux support _vis-à-vis_ placeholders. This still needs fixing.

**Comment by asknet** [comment]
I'm kind of confused, whether this issue is resolved or not? But it's not working for me for C lang.

**Comment by alerque** [comment]
@asknet Note that this issue is still open, no so it's not resolved.

Some languages have built in support for nested comment structures. This plugin supports those languages. C is not one of those lanugages and requires some pseudo-comment syntax markers that need to be re-written on each level change. An attempt was made to do this, but it isn't working properly yet, hence why this issue is still open.

**Comment by alerque** [comment]
#507 seems to have fixed this issues, so thanks to @lincheney for contributing that!
